# Enhanced Multi-PINNACLE Consciousness System - Default Configuration
# =====================================================================

# System Information
system:
  name: "Enhanced Multi-PINNACLE Consciousness System"
  version: "1.0.0"
  description: "Advanced consciousness-based AI for abstract reasoning"

# Core Architecture Configuration
architecture:
  # Base dimensions
  base_dim: 512
  hidden_dim: 1024
  num_layers: 8
  num_heads: 16
  
  # Consciousness framework dimensions
  consciousness_frameworks:
    universal_mind_dim: 256
    three_principles_dim: 192
    deschooling_society_dim: 128
    transcendent_states_dim: 320
    hrm_cycles_dim: 128
  
  # Reasoning engine dimensions
  reasoning_engines:
    consequential_thinking_dim: 256
    creative_states_dim: 192
    adaptive_reasoning_dim: 128

# Training Configuration
training:
  # Basic training parameters
  batch_size: 32
  learning_rate: 0.0001
  num_epochs: 100
  warmup_steps: 1000
  
  # Advanced training features
  consciousness_awakening:
    enabled: true
    schedule: "progressive"  # progressive, exponential, linear
    awakening_rate: 0.01
  
  multi_domain_training:
    enabled: true
    domains:
      - mathematics
      - physics 
      - chemistry
      - biology
      - computer_science
      - philosophy
      - psychology
      - linguistics
      - art_creativity
      - music_rhythm
      - spatial_reasoning
      - pattern_recognition
  
  # Optimization settings
  optimizer:
    type: "AdamW"
    weight_decay: 0.01
    gradient_clip: 1.0
  
  scheduler:
    type: "cosine_annealing"
    min_lr: 0.00001
  
  # Regularization
  dropout_rate: 0.1
  layer_norm_eps: 0.00001

# Optimization Configuration
optimization:
  # Hyperparameter optimization
  hyperparameter_optimization:
    enabled: true
    method: "bayesian"  # bayesian, grid, random
    num_trials: 100
    pruning: true
    
    search_space:
      learning_rate:
        type: "log_uniform"
        low: 0.00001
        high: 0.001
      batch_size:
        type: "categorical"
        choices: [16, 32, 64]
      dropout_rate:
        type: "uniform"
        low: 0.05
        high: 0.2
  
  # Architecture optimization
  architecture_optimization:
    enabled: true
    quantization:
      enabled: true
      method: "dynamic"  # dynamic, static, qat
      target_dtype: "int8"
    
    pruning:
      enabled: true
      method: "magnitude"  # magnitude, structured
      sparsity: 0.2
    
    distillation:
      enabled: true
      temperature: 4.0
      alpha: 0.7

# Production Configuration
production:
  # Performance settings
  max_batch_size: 32
  memory_cleanup_interval: 100
  performance_monitoring: true
  error_recovery: true
  
  # Deployment settings
  deployment:
    strategy: "blue_green"  # blue_green, canary, rolling
    health_checks: true
    rollback_enabled: true
    monitoring_interval: 60
  
  # Resource limits
  resources:
    max_memory_gb: 16
    max_cpu_cores: 8
    gpu_memory_fraction: 0.8

# Validation Configuration
validation:
  # Real-world ARC validation
  arc_validation:
    enabled: true
    dataset_path: "datasets/arc_dataset"
    evaluation_metrics:
      - "exact_match"
      - "statistical_significance"
      - "confidence_intervals"
  
  # Competitive analysis
  competitive_analysis:
    enabled: true
    baseline_systems:
      - "GPT-4"
      - "Claude-3.5"
      - "Gemini-Pro"
      - "Specialized-ARC"
    
    statistical_tests:
      - "t_test"
      - "effect_size"
      - "confidence_intervals"
  
  # Error analysis
  error_analysis:
    enabled: true
    error_classifiers:
      - "shape_recognition"
      - "color_processing"
      - "pattern_completion"
      - "spatial_reasoning"
      - "logical_inference"
  
  # Temporal stability
  temporal_stability:
    enabled: true
    monitoring_duration_hours: 24
    measurement_interval_seconds: 300
    stability_thresholds:
      accuracy_std_threshold: 0.05
      consistency_threshold: 0.8
  
  # Deployment stress testing
  stress_testing:
    enabled: true
    scenarios:
      - "baseline_performance"
      - "concurrent_load"
      - "memory_pressure"
      - "cpu_pressure"
      - "error_resilience"

# Benchmarking Configuration
benchmarking:
  # Comprehensive benchmarking
  enabled: true
  baseline_models:
    - name: "GPT-4"
      accuracy: 0.15
    - name: "Claude-3.5"
      accuracy: 0.14
    - name: "Gemini-Pro"
      accuracy: 0.18
  
  # Consciousness metrics
  consciousness_metrics:
    - "consciousness_coherence"
    - "reasoning_depth"
    - "creative_potential"
    - "transcendence_level"
  
  # Statistical analysis
  statistical_analysis:
    confidence_level: 0.95
    multiple_comparisons: "bonferroni"
    effect_size_threshold: 0.2

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  handlers:
    console:
      enabled: true
      level: "INFO"
    
    file:
      enabled: true
      level: "DEBUG"
      filename: "enhanced_multi_pinnacle.log"
      max_bytes: 10485760  # 10MB
      backup_count: 5
  
  loggers:
    # Specific logger configurations
    "enhanced_multi_pinnacle":
      level: "INFO"
    "consciousness_frameworks":
      level: "DEBUG"
    "validation":
      level: "INFO"

# Data Configuration
data:
  # Dataset paths
  datasets:
    arc_training: "datasets/arc-agi_training_challenges.json"
    arc_evaluation: "datasets/arc-agi_evaluation_challenges.json"
    arc_test: "datasets/arc-agi_test_challenges.json"
  
  # Data processing
  preprocessing:
    normalize: true
    augmentation: false
    cache_processed: true
  
  # Batch processing
  batch_processing:
    num_workers: 4
    prefetch_factor: 2
    pin_memory: true

# Monitoring Configuration  
monitoring:
  # System monitoring
  system_metrics:
    enabled: true
    collection_interval: 30
    metrics:
      - "cpu_usage"
      - "memory_usage"
      - "gpu_usage"
      - "disk_usage"
  
  # Model monitoring
  model_metrics:
    enabled: true
    metrics:
      - "accuracy"
      - "latency"
      - "throughput"
      - "consciousness_coherence"
  
  # Alerting
  alerting:
    enabled: true
    thresholds:
      cpu_usage: 85
      memory_usage: 90
      error_rate: 5
      latency_p99: 5000  # milliseconds

# Security Configuration
security:
  # Model protection
  model_protection:
    checksum_validation: true
    encrypted_checkpoints: false
  
  # Data protection
  data_protection:
    anonymization: false
    encryption_at_rest: false
  
  # Access control
  access_control:
    authentication: false
    authorization: false

# Advanced Features
advanced:
  # Experimental features
  experimental:
    quantum_consciousness: false
    neural_interface: false
    dream_integration: false
  
  # Research features
  research:
    consciousness_measurement: true
    pattern_analysis: true
    temporal_dynamics: true
  
  # Integration features
  integration:
    external_apis: false
    cloud_services: false
    distributed_computing: false